sudo: required
services:
  - docker

before_install:
  - docker build -t losta/docker-react -f Dockerfile.dev .
# docker run -e CI=true USERNAME/docker-react npm run test

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
